// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Persistence.Context;

#nullable disable

namespace Shop.Persistence.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20250921070242_New_Seed_For_Permissons")]
    partial class New_Seed_For_Permissons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "لوازم ورزشی"
                        },
                        new
                        {
                            Id = 2,
                            Name = "لوازم خانگی"
                        },
                        new
                        {
                            Id = 3,
                            Name = "موبایل و تبلت"
                        },
                        new
                        {
                            Id = 4,
                            Name = "لپ‌تاپ و لوازم جانبی"
                        },
                        new
                        {
                            Id = 5,
                            Name = "کامپیوتر و قطعات"
                        },
                        new
                        {
                            Id = 6,
                            Name = "پوشاک و مد"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "مدیریت کاربران"
                        },
                        new
                        {
                            Id = 2,
                            ParentId = 1,
                            Title = "افزودن کاربر"
                        },
                        new
                        {
                            Id = 3,
                            ParentId = 1,
                            Title = "ویرایش کاربر"
                        },
                        new
                        {
                            Id = 4,
                            ParentId = 1,
                            Title = "حذف کاربر"
                        },
                        new
                        {
                            Id = 5,
                            ParentId = 1,
                            Title = "مشاهده کاربران"
                        },
                        new
                        {
                            Id = 6,
                            Title = "مدیریت دسته‌بندی‌ها"
                        },
                        new
                        {
                            Id = 7,
                            ParentId = 6,
                            Title = "افزودن دسته‌بندی"
                        },
                        new
                        {
                            Id = 8,
                            ParentId = 6,
                            Title = "ویرایش دسته‌بندی"
                        },
                        new
                        {
                            Id = 9,
                            ParentId = 6,
                            Title = "حذف دسته‌بندی"
                        },
                        new
                        {
                            Id = 10,
                            ParentId = 6,
                            Title = "مشاهده دسته‌بندی‌ها"
                        },
                        new
                        {
                            Id = 11,
                            Title = "مدیریت محصولات"
                        },
                        new
                        {
                            Id = 12,
                            ParentId = 11,
                            Title = "افزودن محصول"
                        },
                        new
                        {
                            Id = 13,
                            ParentId = 11,
                            Title = "ویرایش محصول"
                        },
                        new
                        {
                            Id = 14,
                            ParentId = 11,
                            Title = "حذف محصول"
                        },
                        new
                        {
                            Id = 15,
                            ParentId = 11,
                            Title = "مشاهده محصولات"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "توپ حرفه‌ای فوتبال سایز ۵",
                            IsActive = true,
                            Name = "توپ فوتبال",
                            Price = 350000
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "کفش مخصوص دویدن",
                            IsActive = true,
                            Name = "کفش ورزشی نایک",
                            Price = 2200000
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "ست دمبل مناسب بدنسازی",
                            IsActive = true,
                            Name = "دمبل ۱۰ کیلویی",
                            Price = 800000
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "طناب مناسب برای تمرین هوازی",
                            IsActive = true,
                            Name = "طناب ورزشی",
                            Price = 150000
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "تشک مخصوص حرکات یوگا و پیلاتس",
                            IsActive = true,
                            Name = "تشک یوگا",
                            Price = 300000
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "دستکش ورزشی ضدلغزش",
                            IsActive = true,
                            Name = "دستکش بدنسازی",
                            Price = 180000
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "دوچرخه ثابت خانگی",
                            IsActive = true,
                            Name = "دوچرخه ثابت",
                            Price = 5500000
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "ست کش تمرینی چندکاره",
                            IsActive = true,
                            Name = "کش مقاومتی",
                            Price = 250000
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "کیسه بوکس ایستاده",
                            IsActive = true,
                            Name = "کیسه بوکس",
                            Price = 1800000
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "ست تیشرت و شلوار ورزشی",
                            IsActive = true,
                            Name = "لباس ورزشی",
                            Price = 400000
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "یخچال فریزر دو قلو سامسونگ",
                            IsActive = true,
                            Name = "یخچال فریزر",
                            Price = 35000000
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "لباسشویی اتوماتیک ۸ کیلویی",
                            IsActive = true,
                            Name = "ماشین لباسشویی",
                            Price = 18000000
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "مایکروویو ۴۰ لیتری",
                            IsActive = true,
                            Name = "مایکروویو",
                            Price = 7500000
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "جاروبرقی ۲۲۰۰ وات",
                            IsActive = true,
                            Name = "جاروبرقی",
                            Price = 4500000
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "پنکه پرقدرت ۳ سرعته",
                            IsActive = true,
                            Name = "پنکه ایستاده",
                            Price = 1200000
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "غذا ساز چندکاره",
                            IsActive = true,
                            Name = "غذا ساز",
                            Price = 3800000
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "اتو بخار حرفه‌ای",
                            IsActive = true,
                            Name = "اتو بخار",
                            Price = 900000
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "کتری برقی استیل ۲ لیتری",
                            IsActive = true,
                            Name = "کتری برقی",
                            Price = 600000
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "قهوه‌ساز فیلیپس",
                            IsActive = true,
                            Name = "قهوه‌ساز",
                            Price = 4200000
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "ظرفشویی ۱۴ نفره بوش",
                            IsActive = true,
                            Name = "ماشین ظرفشویی",
                            Price = 25000000
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "گوشی اپل آیفون 14 پرو مکس",
                            IsActive = true,
                            Name = "آیفون 14",
                            Price = 65000000
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "گوشی سامسونگ گلکسی S23",
                            IsActive = true,
                            Name = "سامسونگ S23",
                            Price = 48000000
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "گوشی شیائومی سری ۱۳",
                            IsActive = true,
                            Name = "شیائومی 13",
                            Price = 25000000
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "تبلت اپل آیپد پرو ۱۲ اینچ",
                            IsActive = true,
                            Name = "تبلت آیپد پرو",
                            Price = 58000000
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "تبلت اندرویدی سامسونگ",
                            IsActive = true,
                            Name = "تبلت سامسونگ Tab S9",
                            Price = 30000000
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "شارژر اصل USB-C",
                            IsActive = true,
                            Name = "شارژر سریع ۶۵ وات",
                            Price = 900000
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 3,
                            Description = "ایرفون بی‌سیم",
                            IsActive = true,
                            Name = "ایرفون بلوتوث",
                            Price = 1500000
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            Description = "کاور ضد ضربه سیلیکونی",
                            IsActive = true,
                            Name = "کاور گوشی",
                            Price = 250000
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "گلس ضدخش",
                            IsActive = true,
                            Name = "محافظ صفحه",
                            Price = 200000
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            Description = "پاوربانک شیائومی",
                            IsActive = true,
                            Name = "پاوربانک ۲۰۰۰۰",
                            Price = 1600000
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 4,
                            Description = "لپ‌تاپ گیمینگ ایسوس",
                            IsActive = true,
                            Name = "لپ‌تاپ ایسوس",
                            Price = 42000000
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "لپ‌تاپ اداری دل",
                            IsActive = true,
                            Name = "لپ‌تاپ دل",
                            Price = 28000000
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            Description = "مک‌بوک پرو ۱۴ اینچ",
                            IsActive = true,
                            Name = "لپ‌تاپ اپل مک‌بوک",
                            Price = 70000000
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            Description = "موس RGB گیمینگ",
                            IsActive = true,
                            Name = "موس گیمینگ",
                            Price = 1200000
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "کیبورد مکانیکال RGB",
                            IsActive = true,
                            Name = "کیبورد مکانیکال",
                            Price = 1800000
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            Description = "کوله ضد ضربه لپ‌تاپ",
                            IsActive = true,
                            Name = "کوله لپ‌تاپ",
                            Price = 900000
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "کول‌پد لپ‌تاپ",
                            IsActive = true,
                            Name = "پایه خنک‌کننده",
                            Price = 800000
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "وب‌کم HD مناسب تماس تصویری",
                            IsActive = true,
                            Name = "وب‌کم",
                            Price = 1500000
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            Description = "هدست با میکروفون",
                            IsActive = true,
                            Name = "هدست گیمینگ",
                            Price = 2200000
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            Description = "هارد اکسترنال ۱ ترابایت",
                            IsActive = true,
                            Name = "هارد اکسترنال",
                            Price = 2500000
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Description = "کارت گرافیک انویدیا",
                            IsActive = true,
                            Name = "کارت گرافیک RTX 4070",
                            Price = 60000000
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Description = "پردازنده نسل ۱۳",
                            IsActive = true,
                            Name = "پردازنده Intel i7",
                            Price = 20000000
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Description = "مادربرد گیمینگ",
                            IsActive = true,
                            Name = "مادربرد ASUS",
                            Price = 15000000
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Description = "حافظه رم باس بالا",
                            IsActive = true,
                            Name = "رم DDR5 16GB",
                            Price = 5000000
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Description = "اس‌اس‌دی پرسرعت",
                            IsActive = true,
                            Name = "SSD 1TB NVMe",
                            Price = 7000000
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Description = "پاور گرین ۷۵۰ وات",
                            IsActive = true,
                            Name = "پاور 750W",
                            Price = 3500000
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 5,
                            Description = "کیس حرفه‌ای",
                            IsActive = true,
                            Name = "کیس گیمینگ",
                            Price = 4500000
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Description = "خنک‌کننده پردازنده",
                            IsActive = true,
                            Name = "کولر پردازنده",
                            Price = 2200000
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Description = "مانیتور 144Hz گیمینگ",
                            IsActive = true,
                            Name = "مانیتور 27 اینچ",
                            Price = 12000000
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "ماوس پد RGB",
                            IsActive = true,
                            Name = "ماوس پد گیمینگ",
                            Price = 400000
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 6,
                            Description = "تی‌شرت نخی راحتی",
                            IsActive = true,
                            Name = "تی‌شرت مردانه",
                            Price = 300000
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 6,
                            Description = "شلوار جین آبی",
                            IsActive = true,
                            Name = "شلوار جین",
                            Price = 800000
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 6,
                            Description = "کفش اسپرت سفید",
                            IsActive = true,
                            Name = "کفش اسپرت",
                            Price = 1200000
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 6,
                            Description = "کاپشن ضد آب",
                            IsActive = true,
                            Name = "کاپشن زمستانی",
                            Price = 2500000
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 6,
                            Description = "پیراهن مردانه کلاسیک",
                            IsActive = true,
                            Name = "پیراهن رسمی",
                            Price = 900000
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 6,
                            Description = "ساعت مچی اسپرت",
                            IsActive = true,
                            Name = "ساعت مچی",
                            Price = 3500000
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 6,
                            Description = "عینک UV400",
                            IsActive = true,
                            Name = "عینک آفتابی",
                            Price = 700000
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 6,
                            Description = "کفش چرمی مردانه",
                            IsActive = true,
                            Name = "کفش مجلسی",
                            Price = 2000000
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 6,
                            Description = "روسری نخی طرح‌دار",
                            IsActive = true,
                            Name = "روسری زنانه",
                            Price = 500000
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 6,
                            Description = "کمربند چرم طبیعی",
                            IsActive = true,
                            Name = "کمربند چرمی",
                            Price = 600000
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "ادمین"
                        },
                        new
                        {
                            Id = 2,
                            Title = "کاربر"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(31)
                        .HasColumnType("nvarchar(31)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Permission", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Permission", "ParentPermission")
                        .WithMany("ChildPermissions")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentPermission");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Product", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shop.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shop.Domain.Entities.User", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Permission", b =>
                {
                    b.Navigation("ChildPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Shop.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
