services:
  sql-server:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: Y
    env_file:
      - /Shop.Api/.env
    ports:
      - 14330:1433
    volumes:
      - sql:/var/opt/mssql/

  redis:
    image: "redis"
    ports:
      - 6379:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - 8080:8080
    depends_on:
      - sql-server
      - redis
    env_file:
      - /Shop.Api/.env
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER=true

volumes:
  sql:
